sudo: false
language: php
php:
  - 5.6
  - 7.0
before_install:
  ## Disable xdebug
  - phpenv config-rm xdebug.ini
  ## Update Composer
  - composer self-update
  ## Install latest version of node
  - nvm install node
install:
  ## Install Composer dependencies
  - composer install --no-interaction --prefer-source
before_script:
  ## Travis configuration
  - cp app/config/config.inc.php.ini app/config/config.inc.php
  ## Install ESLint
  - npm install -g eslint
script:
  - vendor/atoum/atoum/bin/atoum -d tests/units/
  - php tests/functional/api.php
  - vendor/bin/php-cs-fixer --diff --dry-run -v fix
  - eslint web/media/js
notifications:
  irc:
    channels:
      - "irc.mozilla.org#l10n-tools"
    on_success: always
    on_failure: always
    use_notice: true
    template:
      - "%{repository} ; %{commit} (%{author}) : %{message} "
      - "Build details: %{build_url} ; changes: %{compare_url}"
matrix:
  fast_finish: true
